name = "example"
version = "1.0.0"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
meadow = { path = "../meadow" }
glare = ">= 0.1.4 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
